---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r cellcomp_libs, echo=FALSE, results='hide', include=FALSE}
library(dplyr)
library(knitr)
library(tibble)
library(tidyr)

library(xCell)
library(NMF)
```

```{r cellcomp_config, eval=FALSE}
xcell_celltypes <- config$xcell_celltypes_f

```

```{r cellcomp_xcell, results='hide'}
emat_pact <- as.matrix(emat[, grepl('^PACT', colnames(emat))])

xcell <- xCellAnalysis(as.matrix(emat_pact))
xcell_t  <-  read.delim(xcell_celltypes_f)
xcell_lym <- xcell[row.names(xcell) %in% xcell_t$Cell.types[xcell_t$Group=="Lymphocytes"],]
xcell_nonhem <- xcell[row.names(xcell) %in% xcell_t$Cell.types[xcell_t$Group=="Non-Hematopoietic"],]
xcell_nonlym <- xcell[row.names(xcell) %in% xcell_t$Cell.types[xcell_t$Group=="Non-lymphocytes"],]
```

## Cellular Composition {.tabset .tabset-fade}

Cellular composition was calculated using gene set enrichment analysis with X-cell [(Aran et al. Genome Biology 2017)](https://link.springer.com/epdf/10.1186/s13059-017-1349-1?author_access_token=DVtns3PR3raQv61Z6RD4Ym_BpE1tBhCbnbw3BuzI2RO7SD-w75iAhrQ7gjSGzw_zJO6jHEpDqZzy8CsttNZVysUprXQi0WGX-FRCguKfv2d96DcweRBG2ni-01x6T6bpU3-cfZ5nkfzCQeNeg-mMUQ%3D%3D)

### Lymphocytes
```{r cellcomp_lym, fig.width=16, fig.height=8}
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, xcell_lym, subtype_df)
} else {
    annCol <- heatmap_annot(sid, xcell_lym)
}


aheatmap(xcell_lym, scale = "row", annCol=annCol)

```

### Myeloid
```{r cellcomp_nonlym, fig.width=16, fig.height=8}
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, xcell_nonlym, subtype_df)
} else {
    annCol <- heatmap_annot(sid, xcell_nonlym)
}

aheatmap(xcell_nonlym, scale = "row",  annCol=annCol)

```

### Stroma/Epithelial
```{r cellcomp_nonhem, fig.width=16, fig.height=8}
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, xcell_nonhem, subtype_df)
} else {
    annCol <- heatmap_annot(sid, xcell_nonhem)
  
}
aheatmap(xcell_nonhem, scale = "row", annCol=annCol)

```

### Cell types
```{r cellcomp_celltypes}
xcell_t %>%
  dplyr::select(`Full.name`, `Cell.types`, Group, Subgroup) %>%
datatable(
        extensions = dt_ext,
        options = dt_opts,
        rownames=FALSE,
        escape = FALSE
        )

```

### Data
```{r cellcomp_data}
xcell %>%
datatable(
        extensions = dt_ext,
        options = dt_opts,
        rownames=TRUE,
        escape = FALSE
        )
```

## {-}
