---
title: "TME Report"
date: "`r Sys.Date()`"
version: 0.1
output:
  rmdformats::readthedown:
    highlight: tango
    lightbox: true
    gallery: false
    toc_depth: 3
css: ../css/mycss2.css
always_allow_html: yes
editor_options: 
  chunk_output_type: console
params:
  config_yml: "NAMESPACE"
---

```{r main_libs, echo=FALSE, results='hide', include=FALSE}
library(knitr)
library(rmdformats)
```

```{r main_chunkopts, echo=FALSE, results='hide', include=FALSE}
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
	             cache=TRUE,
	             #cache=FALSE,
               cache_rebuild=TRUE,
               cache.path='tme_report_cache/html/',
               fig.path='tme_report_files/figure-html/'
               )
opts_knit$set(width=125)

htmltools::img(src = knitr::image_uri(file.path("../images", "pact2.png")), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```

```{r main_parameters}
config <- read_yaml(params$config_yml)
for(ii in seq_along(config)){
  message(paste0(names(config)[[ii]], ':', config[[ii]]))
  assign(names(config)[ii], config[[ii]])
}

```

```{r summary, child='summary.Rmd', eval=exists('summary_trigger')}
```

```{r child_reports, child='child_reports.Rmd'}
```
TME report version v0.1