---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r pathway_libs, echo=FALSE, results='hide', include=FALSE}
library(dplyr)
library(knitr)
library(tibble)
library(tidyr)

library(GSVA)
library(cluster)
library(parallel)
library(NMF)

source('../src/munge.R')
source('../src/visualization.R')
```

```{r chunkopts, echo=FALSE, results='hise', include=FALSE, eval=FALSE}
opts_chunk$set(echo=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
	             cache=TRUE,
	             #cache=FALSE,
               cache_rebuild=TRUE
)
```

## Pathway Analysis
Gene set enrichment for key pathways using [single-sample GSEA]("https://www.genepattern.org/modules/docs/ssGSEAProjection/4")
```{r pathway_munge}
emat_pact <- as.matrix(emat[, grepl('^PACT', colnames(emat))])
geneset_f <- '../data/genesets.txt'
hgnc_f <- '../data/hgnc_biomart.tsv.gz'

# hgnc
hgnc <- read_tsv(hgnc_f) %>%
  janitor::clean_names()

#read pathway file as list of lists
inlist <- strsplit(readLines(geneset_f), "[[:space:]]+")
pathways <- lapply(inlist, tail, n = -1)
names(pathways) <- lapply(inlist, head, n = 1)
pathways <- lapply(pathways, function(x) symbol_check(x, rownames(emat_pact), hgnc))

# Check for missing genes in mat
missing_l <- list()
for(set_name in names(pathways)){
  ii <- pathways[[set_name]]
  missing <-!ii %in% rownames(emat_pact)
  if(any(missing)){
    missing_gene <- ii[missing]
    missing_l[[set_name]] <- missing_gene
    tmp <- paste(missing_gene, collapse=',')
    warning(paste('WARNING:', set_name, 'missing:', tmp))
  }
}
```

```{r pathway_gsva, results='hide'}
#enrich <- gsva(as.matrix(emat), pathways, method="zscore", verbose=FALSE, parallel.sz=4)
enrich <- gsva(as.matrix(emat_pact), pathways, method="ssgsea", verbose=FALSE, parallel.sz=4)

```

```{r pathway_heatmap}
annCol <- meta %>%
  filter(specimen_id %in% colnames(emat_pact)) %>%
  mutate(Sample = factor(if_else(specimen_id == sid, sid, 'Other'))) %>%
  column_to_rownames('specimen_id') %>%
  dplyr::select(Sample)

if(exists('subtype_df')){
  df <- subtype_df[rownames(annCol),] %>%
    dplyr::select(SSPmod)
  annCol <- rbind(annCol, df)
}

aheatmap(enrich, scale = "row", annCol=annCol)

```

