metadata_tsv: s3://pact-fio/process_exprs/meta_pact_xena.tsv
pact_emat_s3: s3://pact-fio/process_exprs/pact
bc_emat_s3: s3://pact-fio/process_exprs/batch_correct

pact_gid_counts: s3://pact-fio/process_exprs/pact/pact_rsem_raw.exprs.gid.tsv.gz
pact_gid_tpm: s3://pact-fio/process_exprs/pact/pact_rsem_tpm.exprs.tsv.gz
pact_hgnc_tpm: s3://pact-fio/process_exprs/pact/pact_rsem_tpm.exprs.hgnc.tsv.gz
pact_emat_log: s3://pact-fio/process_exprs/pact/pact_eset_log.tsv
blacklist: s3://pact-fio/process_exprs/pact/blacklist.txt

xena_hgnc_tpm: s3://pact-fio/process_exprs/xena/TcgaTargetGtex_rsem_hgnc_tpm.parquet.gz
bc_emat_log: s3://pact-fio/process_exprs/batch_correct/bc_exprs_log.tsv

