---
title: "TME Report"
date: "`r Sys.Date()`"
version: 0.1
output:
  rmdformats::readthedown:
    highlight: tango
    lightbox: true
    gallery: false
    toc_depth: 3
css: css/mycss2.css
always_allow_html: yes
editor_options: 
  chunk_output_type: console
params:
  config_yml: "NAMESPACE"
  metadata_f: "NAMESPACE"
  bctpm_f: "NAMESPACE"
  counts_f: "NAMESPACE"
---

```{r main_libs, echo=FALSE, results='hide', include=FALSE}
library(knitr)
library(rmdformats)
library(here)
library(yaml)
```

```{r main_chunkopts, echo=FALSE, results='hide', include=FALSE}
## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
	             cache=TRUE,
	             #cache=FALSE,
               cache_rebuild=TRUE,
               cache.path='tme_report_cache/html/',
               fig.path='tme_report_files/figure-html/'
               )
opts_knit$set(width=125)
#htmltools::img(src = knitr::image_uri(here("images/pact2.png")),
#               alt = 'logo', 
#               style = 'position:absolute; top:0; right:0; padding:10px;')

here::i_am("main.Rmd")
```

```{r test_local, eval=FALSE}
params <- list(
  config_yml = '/Users/csmith/Documents/fio/tme.yml',
  metadata = '/Users/csmith/git/bioinfo-fio/tme/test_data/meta_pact_xena.tsv',
  bctpm_f = '/Users/csmith/Documents/References/xena/subsets/PactTcgaTargetGtex_rsem_gene_tpm/test_combat_ColonRectum_hgnc.tsv.gz'
)
```

```{r test_render, eval=FALSE}
rmarkdown::render(input='src/tme/R/main.Rmd', output_dir="/tmp/tme", params=list(
  config_yml = '../../../test_data/tme.yml',
  metadata_f = '../../../test_data/meta_pact_xena.tsv',
  bctpm_f = '/Users/csmith/Documents/References/xena/subsets/PactTcgaTargetGtex_rsem_gene_tpm/test_combat_ColonRectum_hgnc.tsv.gz',
  counts_f = '../../../test_data/pact_rsem_raw.exprs.gid.tsv.gz'
 )
)

```

```{r main_parameters}
config <- read_yaml(params$config_yml)
for(ii in seq_along(config)){
  message(paste0(names(config)[[ii]], ':', config[[ii]]))
  assign(names(config)[ii], config[[ii]])
}
message(paste('meta_f:', params$meta_f))
assign('meta_f', params$metadata)
message(paste('bctpm_f:', params$bctpm_f))
assign('bctpm_f', params$bctpm_f)
message(paste('counts_f:', params$counts_f))
assign('counts_f', params$counts_f)

```

```{r summary, child=here('summary.Rmd'), eval=exists('summary_trigger')}
```

```{r child_reports, child=here('child_reports.Rmd')}
```

```{r sessioninfo, include=FALSE}
sink('sessionInfo.txt')
sessionInfo()
sink()
```

TME report version v0.1