---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r pathway_libs, echo=FALSE, results='hide', include=FALSE}
library(dplyr)
library(knitr)
library(tibble)
library(tidyr)

library(GSVA)
library(cluster)
library(parallel)
library(NMF)
library(here)

source(here('munge.R'))
source(here('visualization.R'))
```

```{r chunkopts, echo=FALSE, results='hise', include=FALSE, eval=FALSE}
opts_chunk$set(echo=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
	             cache=TRUE,
	             #cache=FALSE,
               cache_rebuild=TRUE
)
```

## Pathway analysis {.tabset}
Gene set enrichment for key pathways was calculated using [single-sample GSEA]("https://gsea-msigdb.github.io/ssGSEAProjection-gpmodule/v9/index.html").
```{r pathway_config, eval=FALSE}
geneset_f <- '../data/genesets.txt'
hgnc_f <- '../data/hgnc_biomart.tsv.gz'
```

```{r pathway_munge}
emat_pact <- as.matrix(emat[, grepl('^PACT', colnames(emat))])

# hgnc
hgnc <- read.delim(hgnc_f) %>%
  janitor::clean_names()

#read pathway file as list of lists
inlist <- strsplit(readLines(geneset_f), "[[:space:]]+")
pathways <- lapply(inlist, tail, n = -1)
names(pathways) <- lapply(inlist, head, n = 1)
pathways <- lapply(pathways, function(x) symbol_check(x, rownames(emat_pact), hgnc))

# Check for missing genes in mat
missing_l <- list()
for(set_name in names(pathways)){
  ii <- pathways[[set_name]]
  missing <-!ii %in% rownames(emat_pact)
  if(any(missing)){
    missing_gene <- ii[missing]
    missing_l[[set_name]] <- missing_gene
    tmp <- paste(missing_gene, collapse=',')
    warning(paste('WARNING:', set_name, 'missing:', tmp))
  }
}
```

```{r pathway_gsva, results='hide'}
#enrich <- gsva(as.matrix(emat), pathways, method="zscore", verbose=FALSE, parallel.sz=4)
enrich <- gsva(as.matrix(emat_pact), pathways, method="ssgsea", verbose=FALSE, parallel.sz=4)

```

## {.tabset}

### All
```{r pathway_heatmap, fig.width=16, fig.height=8}
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, emat_pact, subtype_df)
} else {
    annCol <- heatmap_annot(sid, emat_pact)
}

aheatmap(enrich, scale = "row", annCol=annCol)

```

### Immune system
```{r pathway_immune, fig.width=16, fig.height=8}
rows = c(
  "TNFA_SIGNALING_VIA_NFKB",
  "TGF_BETA_SIGNALING",
  "IL6_JAK_STAT3_SIGNALING",
  "INTERFERON_GAMMA_RESPONSE",
  "INTERFERON_ALPHA_RESPONSE",
  "EPITHELIAL_MESENCHYMAL_TRANSITION",
  "INFLAMMATORY_RESPONSE",
  "IL2_STAT5_SIGNALING",
  "tcell_inflamed_gep",
  "KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION"
)
mat <- enrich[rows, ]
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, mat, subtype_df)
} else {
    annCol <- heatmap_annot(sid, mat)
}

aheatmap(mat, scale = "row", annCol=annCol)

```

### Driver
```{r pathway_driver, fig.width=16, fig.height=8}
rows = c(
  "P53_PATHWAY",
  "KRAS_SIGNALING_UP",
  "KRAS_SIGNALING_DN",
  "KRAS_SIGNALING_UP",
  "KRAS_SIGNALING_DN",
  "WNT_BETA_CATENIN_SIGNALING",
  "PI3K_AKT_MTOR_SIGNALING",
  "MYC_TARGETS_V1"
)
mat <- enrich[rows, ]
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, mat, subtype_df)
} else {
    annCol <- heatmap_annot(sid, mat)
}

aheatmap(mat, scale = "row", annCol=annCol)

```

### Physiology
```{r pathway_physiology, fig.width=16, fig.height=8}
rows = c(
  "UV_RESPONSE_UP",
  "UV_RESPONSE_DN",
  "ANGIOGENESIS",
  "MSI_DOWN",
  "HYPOXIA",
  "DNA_REPAIR",
  "APOPTOSIS",
  "UNFOLDED_PROTEIN_RESPONSE",
  "MYC_TARGETS_V1",
  "GLYCOLYSIS",
  "REACTIVE_OXYGEN_SPECIES_PATHWAY"
)
  
mat <- enrich[rows, ]
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, mat, subtype_df)
} else {
    annCol <- heatmap_annot(sid, mat)
}

aheatmap(mat, scale = "row", annCol=annCol)

```

### Immune Landscape of Cancer
```{r pathway_thorsson, fig.width=16, fig.height=8}
rows = c(
  "Module3_IFN_score",
  "LIexpression_score",
  "CSF1_response",
  "CHANG_CORE_SERUM_RESPONSE_UP",
  "TGFB_score_21050467"
)
mat <- enrich[rows, ]
if(exists('subtype_df')){
    annCol <- heatmap_annot(sid, mat, subtype_df)
} else {
    annCol <- heatmap_annot(sid, mat)
}

aheatmap(mat, scale = "row", annCol=annCol)

```
Thorsson et al. (2018). The Immune Landscape of Cancer. Immunity, 48(4), 812-830.e14. [doi: 10.1016/j.immuni.2018.03.023](https://pubmed.ncbi.nlm.nih.gov/29628290/)

### Data
```{r pathway_data}
enrich %>%
datatable(
        extensions = dt_ext,
        options = dt_opts,
        rownames=TRUE,
        escape = FALSE
        )
```

## {-}
