---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r stage_input_libs, echo=FALSE, results='hide', include=FALSE}
library(arrow)
library(dplyr)
library(janitor)
library(readr)
library(tibble)
library(tidyr)

library(yaml)
library(here)
library(stringr)

source(here('munge.R'))

```


```{r stage_input_config, eval=FALSE}
manifest_f <- 'test_data/PACT056_T_196454/manifest.yml'
xena_root <- '/Users/csmith/Documents/References/xena'
#mat_f <- file.path(xena_root, 'subsets/PactTcgaTargetGtex_rsem_gene_tpm/exprs_combat_ColonRectum_hgnc.parquet.gz')
#mat_f <- file.path(xena_root, 'subsets/PactTcgaTargetGtex_rsem_gene_tpm/exprs_combat_ColonRectum_hgnc.tsv.gz')
bctpm_f <- file.path(xena_root, 'subsets/PactTcgaTargetGtex_rsem_gene_tpm/test_combat_ColonRectum_hgnc.tsv.gz')
#mat_f <- file.path(xena_root, 'subsets/PactTcgaTargetGtex_rsem_gene_tpm/testpc_combat_Lung_hgnc.tsv.gz')
meta_f <- file.path('test_data/meta_pact_xena.tsv')
goi_f <- 'src/tme/data/pact_goi.tsv'
hgnc_f <- 'src/tme/data/hgnc_biomart.tsv.gz'

```


```{r stage_input_manifest}
manifest <- read_yaml(manifest_f)
pt_dat <- data.frame(
  'PACT ID' = manifest$pipeline$pact_id,
  'Patient' = manifest$pipeline$patient_info$patient.id,
  'Sample' = manifest$pipeline$patient_info$sample.id,
  'Study' = manifest$pipeline$patient_info$study.id,
  'TCGA Study Code' = manifest$pipeline$patient_info$patient.tumorType,
  #'Panel' = manifest$pipeline$panel,
  check.names=FALSE
)

if(pt_dat$`TCGA Study Code` %in% c('COADREAD')){
  subtype_trigger = TRUE
}
sid <- pt_dat[['PACT ID']]
report_title <- paste0("TME Report: ", sid)
```

---
title: "`r report_title`"
---

```{r stage_input_datain_mat}
#, cache.lazy = FALSE}
if(grepl('parquet', bctpm_f)){
    emat_o <- read_parquet(bctpm_f)
} else {
    emat_o <- read.delim(bctpm_f, check.names=FALSE, row.names=1) 
}
emat <- emat_o

if(!any(grepl(sid, colnames(emat)))){
  stop(paste0('ERROR:', sid, 'not found in expression matrix'))
}

```

```{r stage_input_metadata}
meta_o <- read.delim(meta_f) %>%
  janitor::clean_names()

meta <- meta_o %>%
  filter(specimen_id %in% colnames(emat)) %>%
  unite('study_tumor_normal', study, tumor_normal, remove=FALSE) %>%
  mutate(study_tumor_normal = factor(study_tumor_normal)) %>%
  mutate(study = factor(study, levels=c('GTEX', 'PACT', 'TCGA')))

hgnc <- read.delim(hgnc_f) %>%
  mutate(gene=symbol) %>%
  janitor::clean_names()

gtf <- read.delim(gtf_tsv_f) %>%
  mutate(gene = gene_name)

goi_o <- read.delim(goi_f) %>%
  mutate(alias = ifelse(is.na(alias), gene, alias)) %>%
  #dplyr::select(-category) %>%
  distinct() 

hotspots <- read.delim(hotspots_f) %>%
  mutate(gene=hgnc_symbol)

hotspots_goi <- hotspots %>%
  filter(!gene %in% goi_o$gene) %>%
  left_join(hgnc %>% dplyr::select(gene, alias=alias_symbol)) %>%
  mutate(alias = sapply(alias, function(x) str_split(x, '\\|', simplify=TRUE)[1])) %>%
  distinct()
hotspots_goi$category <- 'Hotspot'
goi <- full_join(goi_o, hotspots_goi)


```

```{r stage_emat_qc, include=FALSE} 
dat <- emat 
rmax <- apply(dat, 1, max)
phist <- hist(rmax, breaks=100)
thresh = -9.5
keep <- names(rmax[rmax > thresh])
warning(paste0('Removing ', nrow(dat) - length(keep), ' genes with less than a max(', thresh, ') expression'))
plot(phist)
abline(v=thresh, col='red')

# Subset matrices
emat <- dat[keep, ] 

df_goi <- emat %>% 
  rownames_to_column('gene') %>%
  right_join(goi) %>%
  pivot_longer(starts_with(c('GTEX', 'TCGA', 'PACT')), names_to="specimen_id", values_to = "bcTPM") %>%
  left_join(meta) %>%
  mutate(checkpoint = factor(checkpoint, levels=c('Stimulatory', 'Inhibitory', 'Other')))

```

