---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r subtype_libs, echo=FALSE, results='hide', include=FALSE}
library(dplyr)
library(knitr)
library(tibble)
library(tidyr)

library(CMSclassifier)
library(limma)
library(edgeR)
library(biomaRt)
```

```{r subtype_emat}
#counts_f <- file.path('../test_data/pact_rsem_raw.exprs.gid.tsv.gz')
if(grepl('parquet', counts_f)){
    emat_counts_o <- read_parquet(counts_f)
} else {
    emat_counts_o <- read.delim(counts_f, check.names=FALSE, row.names=1) 
}
emat_counts <- emat_counts_o
```

```{r subtype_cms, eval=pt_dat[['TCGA Study Code']] == 'COADREAD'}
# Subset tumor type samples from emat
dat <- emat_counts[, colnames(emat_counts) %in% meta$specimen_id]

# Get Entrez IDs 
ens <- useEnsembl(biomart='genes', dataset='hsapiens_gene_ensembl', GRCh=37)#, verbose=TRUE)
bm <- getBM(attributes = c('ensembl_gene_id', 'entrezgene_id'), filters = 'ensembl_gene_id', 
            values=rownames(dat), mart=ens)

edat <- dat %>%
  rownames_to_column('ensembl_gene_id') %>%
  inner_join(bm) %>%
  filter(!is.na(entrezgene_id)) %>%
  group_by(entrezgene_id) %>%
  summarize_if(is.numeric, sum) %>%
  ungroup() %>%
  column_to_rownames('entrezgene_id')

# Normalize counts
dge <- edgeR::DGEList(edat)
keep <- edgeR::filterByExpr(dge)
dge <- dge[keep, ]
dge <- edgeR::calcNormFactors(dge)
v1 <- limma::voom(dge)

# Classify
cms <- CMSclassifier::classifyCMS(v1$E,method="SSP")
subtype_df <- cms$predictedCMS %>%
  mutate(Subtype = ifelse(is.na(SSP), 'Unclassified', SSP))

subtype <- subtype_df[sid,]$Subtype

```
