---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r summary_libs, echo=FALSE, results='hide', include=FALSE}
library(dplyr)
library(janitor)
library(readr)
library(tibble)
library(tidyr)

library(yaml)
library(kableExtra)
library(here)

source(here('munge.R'))
source(here('visualization.R'))
```

## Patient Summary
```{r summary_config, eval=FALSE}
tcga_tpm_percentile_min <- .25
tcga_tpm_percentile_max <- .75

```

```{r summary_pttable}
pt_tab <- pt_dat
muts <- goi_tab %>%
  filter(!is.na(`Mutation (AA)`),
         Gene %in% hotspots$hgnc_symbol) %>%
  
  pull(Gene) %>%
  sort()
pt_tab$`Hotspots (SNV)` <- paste(muts, collapse=', ')

if(exists('subtype')){
  pt_tab$Subtype <- subtype
}

pt_tab %>% 
  t() %>%
  knitr::kable('html') %>%
  kable_styling(full_width = F, font_size = 16, position = 'left')

```

```{r summary_goitable}
priority_goi <- goi %>%
  filter(!is.na(priority)) %>%
  pull(gene)

summary_goi_tab <- goi_tab %>%
  dplyr::select(Gene, Alias, Category, `Mutation (AA)`, CNt, `Percentile PACT`, `Percentile TCGA`, `Percentile GTEX`) %>%
  filter(`Percentile TCGA` < tcga_tpm_percentile_min | `Percentile TCGA` > tcga_tpm_percentile_max,
         Gene %in% priority_goi
  ) %>%
  arrange(desc(`Percentile TCGA`))

caption = paste0('Selected genes of interest with low (<', 
                 tcga_tpm_percentile_min,
                 ') or high (>',
                 tcga_tpm_percentile_max,
                 ') gene expression relative to TCGA.'
)
dt_quantile_ramp(summary_goi_tab, c('Percentile PACT', 'Percentile TCGA'), caption, pageLength=999)

```
