name: tme

channels:
  - bioconda
  - conda-forge
  - r
  - nodefaults
dependencies:
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-limma
  - bioconductor-genomicranges
  - bioconductor-gsva
  - gtfparse
  - pandas
  - pyaml
  - python=3.9
  - r-arrow
  - r-base=4.0.5
  - r-corrplot
  - r-devtools
  - r-dt
  - r-here
  - r-janitor
  - r-kableextra
  - r-knitr
  - r-markdown
  - r-nmf
  - r-parallelly
  - r-plotly
  - r-reshape2
  - r-rmarkdown
  - r-rmdformats
  - r-rcolorbrewer
  - r-stringr
  - r-tidyverse
  - r-xcell
  - r-yaml
  - s3fs=0.3
  - pip
  - pip:
    - -e ../
