name: process_exprs

channels:
  - bioconda
  - conda-forge
  - r
  - nodefaults
dependencies:
  - numpy
  - nextflow=21.04
  - patsy
  - pip
  - python=3.9
  - pandas
  - pyyaml
  - s3fs=0.3
  - pip:
    - -e .
