name: bioinfo-fio

channels:
  - bioconda
  - conda-forge
  - r
  - nodefaults
dependencies:
  - bioconductor-gsva
  - bioconductor-deseq2
  - bioconductor-edger
  - fastparquet
  - nextflow=>20.10
  - pandas
  - patsy
  - pkg-config=0.29.2
  - python=3.7
  - pyyaml
  - r-arrow
  - r-base>=4
  - r-rcolorbrewer
  - r-devtools
  - r-dt
  - r-knitr
  - r-parallel
  - r-plotly
  - r-markdown
  - r-nmf
  - r-reshape2
  - r-rmdformats
  - r-rcolorbrewer
  - r-tidyverse
  - r-xcell
  - rclone
  - s3fs
