name: bioinfo-tme

channels:
  - bioconda
  - conda-forge
  - r
  - nodefaults
dependencies:
  - bioconductor-biomart
  - bioconductor-gsva
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-genomicranges
  - nextflow=>20.10
  - pkg-config=0.29.2
  - python=3.7
  - r-arrow
  - r-base>=4
  - r-rcolorbrewer
  - r-devtools
  - r-dt
  - r-knitr
  - r-parallel
  - r-plotly
  - r-markdown
  - r-nmf
  - r-reshape2
  - r-rmdformats
  - r-rcolorbrewer
  - r-stringr
  - r-tidyverse
  - r-xcell
  - r-yaml
  - rclone
