name: process_exprs

channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - fastparquet
  - gtfparse
  - numpy
  - patsy
  - pip
  - python=3.9
  - pandas
  - pyyaml
  - s3fs=0.3
  - pip:
    - -e ../
